
springcloud:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace:
      name: springcloud
    username: cassandra
    password: cassandra

spring:
  cloud:
    config:
      enabled: false